### ISSUE TITLE
forEachAsync issue with walk.js

### ISSUE THREAD

**Issue by NetOperatorWibby** [dpolivy/hbs-utils#5]
Whenever I install a new npm module into my project, `foreachasync` gets updated and the resulting error when running my app results in:

```
/project/node_modules/hbs-utils/node_modules/walk/lib/walk.js:153
      forEachAsync(me._wcurfiles, me._wFilesHandler, me).then(me._wPostFilesHandler);
      ^

TypeError: forEachAsync is not a function
    at Walker._wReadFiles (/project/node_modules/hbs-utils/node_modules/walk/lib/walk.js:153:7)
    at Walker._wReaddirHandler (/project/node_modules/hbs-utils/node_modules/walk/lib/walk.js:166:10)
    at /project/node_modules/hbs-utils/node_modules/walk/lib/walk.js:225:10
    at FSReqWrap.oncomplete (fs.js:123:15)

```

The only fix I've found is to delete `node_modules` and run `npm install` again. I just wish I didn't have to do this every time I add a new module to my project.

**Comment by dpolivy** [comment]
I haven't seen this before, but I just pushed out an updated version (0.0.4) which includes updates for the dependencies to this module. Can you give it a try and see if that resolves the problem?

**Comment by NetOpWibby** [comment]
Nope, still not working. I ran `npm update` and then I installed [handlebars-helpers](https://www.npmjs.com/package/handlebars-helpers). Running `npm start` after that gave the same error.

**Comment by dpolivy** [comment]
What version of node/npm do you have? When you ran update, did it install hbs-utils@0.0.4? Do you have a test case with project.json that you can share with a repro?

I cannot reproduce this.

**Comment by NetOpWibby** [comment]
My apologies for the late response. My Node version is 6.5.0 and npm is 3.10.3. `hbs-utils` didn't install `0.0.4`.

EDIT: Running `npm install` again only gives me `hbs-utils@0.0.3`.

EDIT 2: Running `npm install hbs-utils@0.0.4` gives me an `invalid` warning.

**Comment by dpolivy** [comment]
Not sure what's going on; it's there on npm:

https://www.npmjs.com/package/hbs-utils

Try installing directly from the GitHub repo.  How is it specified in your package.json?

**Comment by NetOpWibby** [comment]
I have it as `"hbs-utils": "^0.0.3"`, so it should've updated just fine.

EDIT: I changed that line to `"hbs-utils": "^0.0.4"`, deleted `node_modules`, ran `npm install` again, everything works. `hbs-utils` also updated. Huh.

**Comment by NetOpWibby** [comment]
All good now! Just a super weird `npm` issue, haha. Thanks for the help!

**Comment by dpolivy** [comment]
Awesome, glad you got it sorted out!

**Comment by tuck182** [comment]
To anyone else who runs across this: I believe this may be due to the naming change in forEachAsync between 2.x (forEachAsync) and 3.x (foreachasync), and case-insensitive filesystems. Our team was getting this error on OS-X but not Linux. We fixed it by adding `foreachasync@^3.0.0` as an explicit project dependency alongside `hbs@~4.0.1`.

**Comment by dpolivy** [comment]
@tuck182 Nice sleuthing! Thanks for sharing!
